[env:esp32dev]
platform  = espressif32@6.9.0
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -Wall
    -Wextra

lib_deps =
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
